Partially fix #188.  Add missing api documentation to readme.
BrainJS/brain.js pull request #194
Opened 2018-04-15 01:57 UTC by robertleeplummerjr

![A GIF or MEME to give some spice of the internet](https://media0.giphy.com/media/UyPpKZScnl7na/giphy.gif)

## Description
This adds some missing documentation.

## Motivation and Context
It works well, is unit tested, and yet nobody knows about it... Till now!

## How Has This Been Tested?
Yes, but way prior to its release.

2018-04-19 04:35 UTC, freddyC requested changes
Let me know if I am wrong on that assumption I haven't used these network types that often.

2018-04-19 04:35 UTC, freddyC commented on README.md
> +var net = new brain.NeuralNetwork();
Is this the correct way to initialize an `RNN`, `LSTM` or a `GRU`?  It seems like `new brain.NeuralNetwork();` is a copy paste mistake.

2018-04-19 04:35 UTC, freddyC commented on README.md
> +var net = new brain.NeuralNetwork();
Same as above comment.

2018-04-20 17:35 UTC, robertleeplummerjr commented
Updated.  Ty for catching!

2018-04-21 18:31 UTC, merged

2018-04-21 18:31 UTC, robertleeplummerjr commented
Since changes were addressed, going to go ahead and merge so we can handle a few outstanding pr's.