Appeal about W3C standardization process
BrainJS/brain.js pull request #338
Opened 2019-01-04 13:37 UTC by DanielMazurkiewicz

## Description
Readme.md file was modified

## Motivation and Context
Getting community to involve in W3C ML standardization process

## How Has This Been Tested?
Bunch of photons were emitted and two specialized photons detectors were used simultaneously to verify if Readme.md looks ok. ;-)

2019-04-11 16:38 UTC, bdistin commented on README.md
> +Brain.js is widely adopted open source machine learning library in javascript world. There are several reasons for it, but most notable is **simplicity of usage while not sacrafizing performance**.
sacrafizing => sacrificing

2019-04-11 16:42 UTC, bdistin requested changes

2019-04-11 16:42 UTC, bdistin commented on README.md
> +Brain.js is widely adopted open source machine learning library in javascript world. There are several reasons for it, but most notable is **simplicity of usage while not sacrafizing performance**.
```suggestion
Brain.js is a widely adopted open source machine learning library in the javascript world. There are several reasons for it, but most notable is **simplicity of usage while not sacrificing performance**.
```

2019-04-11 16:42 UTC, bdistin commented on README.md
> +Brain.js is widely adopted open source machine learning library in javascript world. There are several reasons for it, but most notable is **simplicity of usage while not sacrafizing performance**.
```suggestion
Brain.js is a widely adopted open source machine learning library in the javascript world. There are several reasons for it, but most notable is **simplicity of usage while not sacrificing performance**.
```

2019-10-04 03:37 UTC, mubaidr approved these changes

2019-10-04 03:42 UTC, merged